### ISSUE TITLE
Опечатка в комментарии к Hello World

### ISSUE THREAD

**Issue by DobriniaMerk** [oldteamhost/ncurses-russian#1]
[Здесь:](https://github.com/oldteamhost/ncurses-russian/wiki/2.-Hello-World-!!!#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-1-hello-world-)
```cpp
endwin();                   /* Завершить режим проклятий */
```
Название библиотеки случайно перевелось.

**Comment by Lomasterrrr** [comment]
Спасибо исправил!

**Comment by DobriniaMerk** [comment]
Теперь там запускается режим curses, но завершается режим ncurses.

**Comment by Lomasterrrr** [comment]
всё теперь точно
